version: "3"

services:

  dovecot:
    build: ./dovecot
    ports:
      - "127.0.0.1:993:993"
    networks:
      - mail
    volumes:
      - ./data/Maildir:/Maildir

  keycloak:
    build: ./keycloak/
    networks:
      - web
      #- sso
    volumes:
      - ./data/keycloak:/opt/keycloak/standalone/data
    environment:
      - HOST_NAME
      - ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}

  sogo:
    build: ./sogo/
    networks:
      - web
      - mail
    depends_on:
      - sogo_db
      - dovecot
    volumes:
      - ./sogo/idp-metadata.xml:/etc/sogo/idp-metadata.xml:ro
    environment:
      - HOST_NAME
      - LDAP_BIND_PASSWORD=${SOGO_LDAP_BIND_PASSWORD}
      - DB_USER=${SOGO_DB_USER}
      - DB_PASSWORD=${SOGO_DB_PASSWORD}

  sogo_db:
    image: postgres:13.2
    networks:
      - mail
    volumes:
      - ./data/sogo/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_INITDB_ARGS
      - POSTGRES_USER=${SOGO_DB_USER}
      - POSTGRES_PASSWORD=${SOGO_DB_PASSWORD}

  proxy:
    image: nginx:1.19
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NGINX_HOST=localhost:9090
      - NGINX_PORT=80
    ports:
      - "127.0.0.1:9090:80"
    networks:
      - web

networks:
  web:
  mail:
  #sso:

# vim: sw=2
