#!/bin/bash

pass_vars=(
    #KEYCLOAK_DB_PASS
    KEYCLOAK_ADMIN_PASS
    SOGO_DB_PASSWORD
    SOGO_LDAP_BIND_PASSWORD
)

for var in ${pass_vars[@]}; do
    sed -i.bak \
        -e "s#$var=.*#$var=$(pwgen 16 1)#g" \
        "$(dirname "$0")/.env"
done
